export const DEFAULT_SETTINGS = {
  scrollDelayMs: 500,
  activeProfileId: "js-full-stack-sde",
  profiles: [
    {
      id: "js-full-stack-sde",
      name: "JS Full Stack / SDE",
      primaryKeywords: [
        "javascript developer",
        "js developer",
        "typescript developer",
        "frontend developer",
        "front end developer",
        "front-end developer",
        "react developer",
        "react.js developer",
        "reactjs developer",
        "next.js developer",
        "nextjs developer",
        "node.js developer",
        "nodejs developer",
        "node developer",
        "node backend",
        "backend node",
        "backend javascript",
        "backend typescript",
        "express backend",
        "nestjs backend",
        "mern stack",
        "mern developer",
        "full stack javascript",
        "fullstack javascript",
        "full-stack javascript",
        "full stack developer",
        "full-stack developer",
        "sde frontend",
        "sde full stack",
        "sde javascript"
      ],
      supportingKeywords: [
        "javascript",
        "js",
        "typescript",
        "react",
        "react.js",
        "reactjs",
        "next.js",
        "nextjs",
        "node",
        "node.js",
        "nodejs",
        "express",
        "express.js",
        "nestjs",
        "nest.js",
        "frontend",
        "front end",
        "front-end",
        "full stack",
        "full-stack",
        "fullstack",
        "web developer"
      ],
      locationKeywords: [
        "gurgaon",
        "gurugram",
        "noida",
        "delhi ncr",
        "ncr"
      ],
      hiringKeywords: [
        "hiring",
        "we are looking",
        "job opening",
        "opening",
        "refer",
        "referral",
        "recruiter",
        "send your resume",
        "share your cv",
        "apply"
      ],
      exclusionKeywords: [
        ".net",
        "dotnet",
        "dot net",
        "java"
      ]
    },
    {
      id: "gen-ai-engineer",
      name: "Gen AI / AI Engineer",
      primaryKeywords: [
        "gen ai engineer",
        "generative ai engineer",
        "ai engineer",
        "llm engineer",
        "large language model engineer",
        "prompt engineer",
        "rag engineer",
        "ai application engineer",
        "ai product engineer",
        "machine learning engineer",
        "ml engineer"
      ],
      supportingKeywords: [
        "gen ai",
        "generative ai",
        "llm",
        "large language model",
        "rag",
        "langchain",
        "langgraph",
        "openai",
        "chatgpt",
        "prompt engineering",
        "vector database",
        "embeddings",
        "machine learning",
        "ml",
        "ai"
      ],
      locationKeywords: [
        "gurgaon",
        "gurugram",
        "noida",
        "delhi ncr",
        "ncr",
        "remote"
      ],
      hiringKeywords: [
        "hiring",
        "we are looking",
        "job opening",
        "opening",
        "refer",
        "referral",
        "recruiter",
        "send your resume",
        "share your cv",
        "apply"
      ],
      exclusionKeywords: []
    }
  ]
};
